# Generated by Django 2.0.6 on 2019-04-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verduleria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compra',
            new_name='Venta',
        ),
    ]
