# Generated by Django 2.0.6 on 2019-04-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verduleria', '0002_auto_20190411_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='fechaCompra',
        ),
        migrations.AddField(
            model_name='venta',
            name='fechaCompra',
            field=models.DateField(default=123),
            preserve_default=False,
        ),
    ]
