# Generated by Django 2.0.6 on 2019-04-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verduleria', '0004_auto_20190411_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='fechaVenta',
            new_name='fechaCompra',
        ),
    ]
